version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  prepare_rabbit:
    docker:
      - image: rabbitmq
        name: video-server-rabbitmq
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    steps:
      - run: echo "OK"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - prepare_rabbit
