version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  prepare_rabbit:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Test docker-compose
          command: |
            docker-compose up -d
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - prepare_rabbit
