version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "!!!"
  test-video-server-app:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Cài đặt pytest
          command: |
            pip install pytest requests
      - run:
          name: Chuẩn bị source code test từ github
          command: |
            git clone https://github.com/bngoc1307/Nhom04_CCPTPM
            cd Nhom04_CCPTPM
      - run:
          name: Bắt đầu chạy test
          command: |
            python -m pytest

workflows:
  build_and_test:
    jobs:
      - test-video-server-app
