version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  preparedocker:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run:
          name: Install docker-compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            wget "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -O docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - preparedocker
